### ISSUE TITLE
[Feat] 내 연차 페이지 UI 작업

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#1]
## 💡 기능 설명

로그인 후 연차 메뉴 클릭 시 진입하는 연차 화면 UI 작업

## 📝 ToDo

- [x] 내 연차 현황 UI
- [x] 연차 신청 내역 리스트
- [x] 연차 신청 아이템
- [x] 연차 사용 내역 리스트
- [x] 연차 사용 아이템
- [x] 연차 신청 취소 메뉴 
- [x] 연차 등록하기 버튼
