### ISSUE TITLE
[Style] 휴가 페이지 목록 테이블 형식으로 UI 변경 

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#21]
## 💡 기능 설명

휴가  페이지에 있는 List UI Table UI 로 변경

## 📝 ToDo

- [x] 휴가 신청 내역 변경
- [x] 휴가 사용 내역 변경
- [x] 연차 > 휴가로 이름 변경
