### ISSUE TITLE
[Feat] 내정보 페이지 UI 작업

### ISSUE THREAD

**Issue by HyunJunPark0** [FC-MINI-6/mini-project-FE#25]
## 💡 기능 설명

내정보 페이지 UI

## 📝 ToDo

- [ ] 이름, 이메일, 직급, 입사일, 전화번호 Input 추가
- [ ] 전화번호 수정 버튼
- [ ] 비밀번호 수정 Modal
