### ISSUE TITLE
[Feat] 휴가/당직 처리 결과 알림 기능 구현 

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#27]
## 💡 기능 설명

휴가 / 당직 승인, 반려 처리 시 발생하는 알림 기능

## 📝 ToDo

- [x] 알림 팝업 ui
- [x] 알림 목록
- [x] 알림 카운트 뱃지
- [x] 알림 추가
- [x] 알림 읽음 처리
