### ISSUE TITLE
[Feat] 연차 등록 모달 UI 작업

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#3]
## 💡 기능 설명

연차 등록 모달 UI 작업

## 📝 ToDo

- [x] 연차 타입 선택 라디오 버튼
- [x] 날짜 선택 DatePicker 추가
- [ ] 선택 날짜 표시
- [x] 사유 입력 Input
- [x] 취소 버튼
- [x] 등록 버튼

**Comment by EungBug** [comment]
선택 날짜 표시 UI 불필요해보여서 뺐습니다.
