### ISSUE TITLE
[Feat] 유저 상태관리 추가

### ISSUE THREAD

**Issue by HyunJunPark0** [FC-MINI-6/mini-project-FE#30]
## 💡 기능 설명

stores/userStore.ts

로그인,마이페이지 유저 상태관리 작업

## 📝 ToDo

- [x] zustand를 사용해서 userStore.ts 추가
- [x] 로그인 페이지 응답값으로 유저 데이터 관리
- [x] 마이페이지에서 데이터 사용
