### ISSUE TITLE
[Feat] 휴가페이지 내역 조회 API 연동

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#34]
## 💡 기능 설명

휴가 > 휴가 신청 내역 조회 API 연동
휴가 > 휴가 사용 내역 조회 API 연동

## 📝 ToDo

- [x] 휴가 내역 조회 API 연동
- [x] 휴가 신청 상태 리스트 필터링
- [x] 휴가 사용 상태 리스트 필터링
- [x] API 통신 시 로딩 UI 추가 필요
- [x] 남은 연차, 사용연차 일 수 표시
