### ISSUE TITLE
[Feat] 당직 페이지 조회 API 연동

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#35]
## 💡 기능 설명

당직 > 당직 신청 내역 조회 API 연동
당직 > 당직 사용 내역 조회 API 연동

## 📝 ToDo

- [x] 당직 내역 조회 API 연동
- [x] 당직 신청 상태 리스트 필터링
- [x] 당직 사용 상태 리스트 필터링
- [x] API 통신 시 로딩 UI 추가 필요
