### ISSUE TITLE
[Feat] 당직 신청 API 연동

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#36]
## 💡 기능 설명
당직 신청 API 연동

## 📝 ToDo

- [x] 당직 신청 api 연동
- [x] api 응답 결과 성공 시 모달 추가
- [x] api 응답 결과 실패 시 오류 모달 추가
