### ISSUE TITLE
[Feat] 내 당직 페이지 UI 작업

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#4]
## 💡 기능 설명

메뉴 > 당직 > 당직 화면 UI 작업

## 📝 ToDo
 
- [x] 당직 신청 내역 
- [x] 당직 신청 아이템
- [x] 당직 기록 내역
- [x] 당직 기록 아이템
- [x] 당직 신청 취소 메뉴
- [x] 당직 신청 버튼
