### ISSUE TITLE
[Feat] 당직 취소 기능

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#41]
## 💡 기능 설명

당직 취소 API 연동

## 📝 ToDo

- [x] 당직 취소 API 연동
- [x] 당직 취소 성공 시 성공 모달 및 리스트 갱신
- [x] 당직 실패 시 에러 모달 추가
