### ISSUE TITLE
[Feat]  캘린더 일정 조회 기능

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#45]
## 💡 기능 설명

홈 > 캘린더 일정

## 📝 ToDo

- [x] 유저 목록 조회 API 연동
- [x] 일정 조회 API 연동
- [x] 사용자 선택 별 필터링 기능
- [x] 날짜 별 필터링 기능
- [x] 응답 데이터 가공
