### ISSUE TITLE
[Feat] 로그인 API 연동

### ISSUE THREAD

**Issue by HyunJunPark0** [FC-MINI-6/mini-project-FE#46]
## 💡 기능 설명

로그인 API 연동 작업

## 📝 ToDo

- [x] 로그인 API 연동.
- [x] interface types폴더에 분류.
- [x] 로그인 -> 홈화면으로 이동.
