### ISSUE TITLE
[Feat] 회원가입 API 연동

### ISSUE THREAD

**Issue by HyunJunPark0** [FC-MINI-6/mini-project-FE#47]
## 💡 기능 설명

회원가입 API 연동 작업

## 📝 ToDo

- [x] 회원가입 API 연동.
- [x] interface types폴더에 분류.
- [x] 가입성공 -> 로그인 페이지로 이동.
