### ISSUE TITLE
[Feat] 홈 화면 UI 작업

### ISSUE THREAD

**Issue by EungBug** [FC-MINI-6/mini-project-FE#6]
## 💡 기능 설명

홈 화면 전체 일정 캘린더 UI 와 선택 시 일정 아이템 UI 작업

## 📝 ToDo

- [x] 전체 일정 캘린더 UI 반영
- [x] 유저 목록 드롭다운 추가
- [x] 일정 아이템 UI
